name: CI/CD for DevOps

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Тесты Frontend
      - name: Run frontend tests
        run: |
          npm install
          npm run test

      # 3. Собираем Frontend
      - name: Build & Push Frontend
        if: success()
        run: |
          npm install
          npm run build